name: Deploy to Production

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/project
            git remote set-url origin git@github.com:Walenhstein/buyFlatsService.git
            git reset --hard HEAD
            git pull origin main
            
            cd server
            docker build -t my-backend .
            docker stop backend-app || true
            docker rm backend-app || true
            docker run -d --name backend-app -p 3000:3000 --env-file .env my-backend
            
            cd ../client
            docker run --rm -v .:/app -w /app node:20-alpine npm run build
            
            sudo systemctl restart nginx
